const weatherActionTypes = {
  FETCH_WEATHER_BEGIN: 'FETCH_WEATHER_BEGIN',
  FETCH_WEATHER_SUCCESS: 'FETCH_WEATHER_SUCCESS',
  FETCH_WEATHER_ERROR: 'FETCH_WEATHER_ERROR',
  SAVE_LOCAL_STORAGE: 'SAVE_LOCAL_STORAGE',
};

export default weatherActionTypes;
